# dotstorage cid verifier wrangler config.
name = "dotstorage-cid-verifier"
main = "./dist/worker.js"
compatibility_date = "2022-07-01"
compatibility_flags = [ "url_standard" ]
no_bundle = true

[build]
command = "npm run build"

[vars]
DEBUG = "true"
ENV = "dev"
GOOGLE_EVALUATE_SAFE_CONFIDENCE_LEVELS = [ "CONFIDENCE_LEVEL_UNSPECIFIED", "SAFE" ]

# PROD!
[env.production]
# name = "dotstorage-cid-verifier-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "cid-verifier.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [
  { binding = "CID_VERIFIER_RESULTS", id = "9be91fbb7fe34afea6629732981fc8e9" },
  { binding = "DENYLIST", id = "785cf627e913468ca5319523ae929def" }
]

[env.production.vars]
DEBUG = "false"
ENV = "production"

# Staging!
[env.staging]
# name = "dotstorage-cid-verifier-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "cid-verifier-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [
  { binding = "CID_VERIFIER_RESULTS", id = "c742e87b92da4a77bdce7de8105778ff" },
  { binding = "DENYLIST", id = "f4eb0eca32e14e28b643604a82e00cb3" }
]

[env.staging.vars]
DEBUG = "true"
ENV = "staging"

# Test!
[env.test]
workers_dev = true
kv_namespaces = [
  { binding = "CID_VERIFIER_RESULTS" },
  { binding = "DENYLIST" }
]

[env.test.vars]
GOOGLE_CLOUD_API_URL = 'http://127.0.0.1:9111'
GOOGLE_CLOUD_API_KEY = 'TEST'
DEBUG = "true"
ENV = "test"
GOOGLE_EVALUATE_SAFE_CONFIDENCE_LEVELS = [ "CONFIDENCE_LEVEL_UNSPECIFIED", "SAFE" ]
