# dotstorage denylist wrangler config.
name = "dotstorage-denylist"
main = "./dist/worker.js"
compatibility_date = "2022-09-27"
compatibility_flags = [ "url_standard" ]
no_bundle = true

[build]
command = "npm run build"

[vars]
DEBUG = "true"
ENV = "dev"

# PROD!
[env.production]
# name = "dotstorage-denylist-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "denylist.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [
  { binding = "DENYLIST", id = "785cf627e913468ca5319523ae929def" }
]

[env.production.vars]
DEBUG = "false"
ENV = "production"

# Staging!
[env.staging]
# name = "dotstorage-denylist-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "denylist-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [
  { binding = "DENYLIST", id = "f4eb0eca32e14e28b643604a82e00cb3", preview_id = "f4eb0eca32e14e28b643604a82e00cb3" }
]

[env.staging.vars]
DEBUG = "true"
ENV = "staging"

# Test!
[env.test]
workers_dev = true
kv_namespaces = [
  { binding = "DENYLIST" }
]

[env.test.vars]
DEBUG = "true"
ENV = "test"
