# dotstorage edge gateway wrangler config.
name = "dotstorage-edge-gateway"
main = "./dist/worker.mjs"
compatibility_date = "2022-07-01"
compatibility_flags = [ "url_standard" ]
no_bundle = true

[build]
command = "npm run build"

# miniflare
[vars]
IPFS_GATEWAYS = "[\"http://127.0.0.1:9081\"]"
GATEWAY_HOSTNAME = 'ipfs.localhost:8787'
EDGE_GATEWAY_API_URL = 'http://localhost:8787'
DEBUG = "true"
ENV = "dev"

# PROD!
[env.production]
# name = "dotstorage-edge-gateway-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "dag.haus/ipfs/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipfs.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "ipfs.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipfs.dag.haus", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "dag.haus/ipns/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipns.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipns.dag.haus", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [{ binding = "DENYLIST", id = "785cf627e913468ca5319523ae929def" }]

[env.production.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf.dag.haus\", \"https://pinata.dag.haus\"]"
GATEWAY_HOSTNAME = 'ipfs.dag.haus'
EDGE_GATEWAY_API_URL = 'https://api.nftstorage.link'
DEBUG = "false"
ENV = "production"

# TODO: Should point to general API in the future
[[env.production.services]]
binding = "API"
type = "service"
service = "nftstorage-link-api-production"
environment = "production"

[[env.production.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_WINNER_PRODUCTION"
name = "PUBLIC_RACE_WINNER"

[[env.production.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_TTFB_PRODUCTION"
name = "PUBLIC_RACE_TTFB"

[[env.production.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_STATUS_CODE_PRODUCTION"
name = "PUBLIC_RACE_STATUS_CODE"

# Staging!
[env.staging]
# name = "gateway-nft-storage-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "*.ipfs-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "ipfs-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipfs-staging.dag.haus", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipns-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" },
  { pattern = "*.ipns-staging.dag.haus", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
]
kv_namespaces = [{ binding = "DENYLIST", id = "f4eb0eca32e14e28b643604a82e00cb3" }]

[env.staging.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf.dag.haus\", \"https://pinata.dag.haus\"]"
GATEWAY_HOSTNAME = 'ipfs-staging.dag.haus'
EDGE_GATEWAY_API_URL = 'https://api.nftstorage.link'
DEBUG = "true"
ENV = "staging"

# TODO: Should point to general API in the future
[[env.staging.services]]
binding = "API"
type = "service"
service = "nftstorage-link-api-staging"
environment = "production"

[[env.staging.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_WINNER_STAGING"
name = "PUBLIC_RACE_WINNER"

[[env.staging.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_TTFB_STAGING"
name = "PUBLIC_RACE_TTFB"

[[env.staging.unsafe.bindings]]
type = "analytics_engine"
dataset = "PUBLIC_RACE_STATUS_CODE_STAGING"
name = "PUBLIC_RACE_STATUS_CODE"

# Test!
[env.test]
workers_dev = true
kv_namespaces = [{ binding = "DENYLIST" }]

[env.test.vars]
IPFS_GATEWAYS = "[\"http://127.0.0.1:9081\", \"http://localhost:9082\", \"http://localhost:9083\"]"
GATEWAY_HOSTNAME = 'ipfs.localhost:8787'
EDGE_GATEWAY_API_URL = 'http://localhost:8787'
DEBUG = "true"
ENV = "test"
