name: ipfs-gateway-race
on:
  push:
    branches:
      - main
    paths:
      - 'packages/ipfs-gateway-race/**'
      - '.github/workflows/ipfs-gateway-race.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/ipfs-gateway-race/**'
      - '.github/workflows/ipfs-gateway-race.yml'
      - 'pnpm-lock.yaml'

jobs:
  check:
    name: Typecheck race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/ipfs-gateway-race/tsconfig.json

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - name: Test
        run: pnpm --filter ipfs-gateway-race test

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: tag-release
        with:
          path: packages/ipfs-gateway-race
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: ipfs-gateway-race
      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2.0.1
        if: ${{ steps.tag-release.outputs.releases_created }}
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        if: ${{ steps.tag-release.outputs.releases_created }}
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm install
        if: ${{ steps.tag-release.outputs.releases_created }}
      - name: NPM Publish
        if: ${{ steps.tag-release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          cd packages/ipfs-gateway-race
          npm publish --access=public
